### ISSUE TITLE
Halfway working...

### ISSUE THREAD

**Issue by Leadwerks** [lee-seungjae/VSCodeLuaDebug#23]
- I can use debuggee.print to print messages that appear in the VSCode debugger.
- I can pause the application from VSCode.
- I can call debuggee.enterDebugLoop() to pause the application.

However:
- Breakpoints set in VSCode are ignored.
- When the application is paused, no information about the callstack or variables is shown in VSCode.

I am using LuaJIT 2.0.2, sol3, LuaSocket, and dkjson, all x64 builds, on Windows 10, with VS2019. Code files are executed by loading them and calling do_string(), with the chunkname set to the full script file path.

**Comment by Leadwerks** [comment]
In the function handlers.setBreakpoints(req) I can verify that the correct breakpoints are being set from VSCode, but they are not getting triggered when that line is executed.

**Comment by Leadwerks** [comment]
Even more strange, if I set a breakpoint on this line in my main loop, that DOES work. But it only works on this one line of code, and all other breakpoints are ignored:
```debuggee.poll()```

**Comment by Leadwerks** [comment]
It seems that the breakpoints only work if they are on a function call to a Lua function. Every line in this  code has a breakpoint but the only one that gets caught is on the call to the empty Lua function dosomething():
```--Main loop
while window:Closed() == false do

	dosomething()
	local a = 1
	local b = a + 2

	world:Update()
	world:Render(framebuffer)

end

**Comment by Leadwerks** [comment]
Similar issue here:
https://github.com/devcat-studio/VSCodeLuaDebug/issues/13

I tried this right after creating the Lua state, but it changed nothing:
```
#ifdef _DEBUG
		luaJIT_setmode(L,0,LUAJIT_MODE_OFF);
#endif
```

**Comment by Leadwerks** [comment]
Using regular Lua 5.1.5 the breakpoints work but I get a "Debug Assertion Failed" error in _CrtIsValidHeapPoint(block) after some time. I suspect the LuaSocket DLL is causing this.

**Comment by Leadwerks** [comment]
Okay, you MUST build Lua as a DLL for this to work. Make sure LuaSocket is using the exact same lib/DLL as your main program. But it works great now! This is really amazing.

**Comment by UltraEngine** [comment]
Not experiencing this problem with Lua 5.4, compiled as a static library.
